### ISSUE TITLE
Exception handling throws exception while creating detailed message

### ISSUE THREAD

**Issue by iamjuing** [StateSmith/StateSmith#204]
Cause example: `via exit done / action();`
StateSmith: 0.9.4-alpha

System.NotImplementedException: The method or operation is not implemented.
   at StateSmith.SmGraph.Visitors.ShortDescribingVisitor.Visit(Vertex v) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\SmGraph\Visitors\ShortDescribingVisitor.cs:line 23
   at StateSmith.SmGraph.Visitors.VertexVisitor.Visit(ChoicePoint v) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\SmGraph\Visitors\VertexVisitor.cs:line 16
   at StateSmith.SmGraph.ChoicePoint.Accept(VertexVisitor visitor) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\SmGraph\ChoicePoint.cs:line 16
   at StateSmith.SmGraph.Visitors.VertexPathDescriber.Describe(Vertex vertex) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\SmGraph\Visitors\VertexPathDescriber.cs:line 28
   at StateSmith.Runner.ExceptionPrinter.TryBuildingCustomExceptionDetails(Exception ex) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\ExceptionPrinter.cs:line 87
   at StateSmith.Runner.ExceptionPrinter.BuildExceptionDetails(StringBuilder sb, Exception exception, Boolean additionalDetail, Int32 depth) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\ExceptionPrinter.cs:line 42
   at StateSmith.Runner.ExceptionPrinter.PrintException(Exception exception) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\ExceptionPrinter.cs:line 30
   at StateSmith.Runner.SmRunnerInternal.HandleException(Exception e) in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\SmRunnerInternal.cs:line 69
   at StateSmith.Runner.SmRunnerInternal.Run() in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\SmRunnerInternal.cs:line 59
   at StateSmith.Runner.SmRunner.Run() in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\SmRunner.cs:line 87

**Comment by adamfk** [comment]
Thanks for the full stack trace. Should have a fix today. I forgot to add some vertices to ShortDescribingVisitor. Will add a specification test as well to make sure this remains fixed.

One thing that puzzles me though is that `via exit done / action();` should be invalid syntax. You should see an error like:

```
StateSmith.SmGraph.DiagramEdgeParseException : no viable alternative at input ' /' at line 1 column 14. Offending symbol: `/`.
mismatched input '/' expecting <EOF> at line 1 column 14. Offending symbol: `/`.
```

The correct syntax would be: `/ action(); via exit done` or `/ { action(); } via exit done`.

Can you provide a small screen shot?

**Comment by adamfk** [comment]
@iamjuing Can you try using version `0.9.4-alpha-fix-2`? You should get a new proper exception.

Here's an explanation:
1. an exception (probably due to validation) is being thrown in StateSmith.
2. StateSmith is trying to provide a helpful error message so it uses the `ShortDescribingVisitor` class to describe the vertex.
3. `ShortDescribingVisitor` wasn't prepared for a vertex like `ExitPoint` and throws its own exception masking the original.

I added tests and reworked the Visitor pattern implementation so that this can't happen again - StateSmith won't compile unless `ShortDescribingVisitor` handles all vertex types.

**Comment by iamjuing** [comment]
Output of `via exit done / action();` with `0.9.4-alpha-fix-2`
```
Failed parsing diagram edge
from: ROOT.operational.positioning
to:   ROOT.operational.<ChoicePoint>()
Edge label: `via exit done / action();
`
Reason(s): no viable alternative at input ' /' at line 1 column 14. Offending symbol: `/`.
           mismatched input '/' expecting <EOF> at line 1 column 14. Offending symbol: `/`.
Edge diagram id: pIgViPkD7wSpJ1tPC_ht-865


You can enable exception detail dumping by setting `RunnerSettings.dumpErrorsToFile` to true.
StateSmith Runner - Finished with failure.

System.Exception: Finished with failure
   at StateSmith.Runner.SmRunner.Run() in C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\SmRunner.cs:line 90
```

**Comment by iamjuing** [comment]
`/ action(); via exit done` works well although not very straightforward.
I would say it does not fit well the grammar, and is even problem prone as it mixes with the user's code.

Consider `/ via(); via exit done` ... this fails the genration as well.
Keywords shall be separated from the user's code which `via exit done [is_cond_true()] / action();` meets well I believe.
Please, consider the change.

**Comment by iamjuing** [comment]
One more comment to exception dump.
Please, notice `C:\Users\akruck\Documents\code\ss\StateSmith\src\StateSmith\Runner\`
This is revealing your local environment which might be undesirable.

I don't know why, but I though the Nuget package contains the source code, so it shall not contain anything like this.

**Comment by adamfk** [comment]
Added a discussion space for entry/exit point grammar: https://github.com/StateSmith/StateSmith/discussions/210

`/ via(); via exit done` currently fails code generation because of a [lexing rule](https://github.com/StateSmith/StateSmith/issues/211). I think it should be an easy fix.

Thanks for the heads up about my computer paths. I have a [ticket open](https://github.com/StateSmith/StateSmith/issues/124) for this. Hopefully a C# developer will help in the future :)
