### ISSUE TITLE
improve exceptions

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#38]
There are a lot of good error messages right now, but there are still a number of assert like exceptions that aren't helpful (yet) and don't provide enough detail to diagnose.

The below error message is printed if your diagram is lacking an initial state.

Previous:
```
StateSmith Runner - Compiling file: `LaserTagMenu1/LaserTagMenu1Sm.graphml`
Exception InvalidOperationException : Sequence contains no elements
StateSmith Runner - finished with failure.
```

New (as of [efbfd4c](https://github.com/StateSmith/StateSmith/commit/efbfd4c3e6002dbd2eec81fa0d3efe05e6c00a3c))
```
StateSmith Runner - Compiling file: `src/Tutorial1Sm.graphml`
VertexValidationException: State machines must have exactly 1 initial state. Actual count: 0.
    Vertex
    Path: Statemachine{Tutorial1Sm}
    Diagram Id: n0
    Children count: 3
    Behaviors count: 0
    Incoming transitions count: 0

Additional exception detail dumped to file: Tutorial1Sm.graphml.err.txt
StateSmith Runner - finished with failure.
```

`Tutorial1Sm.graphml.err.txt`:
```
VertexValidationException: State machines must have exactly 1 initial state. Actual count: 0.
    Vertex
    Path: Statemachine{Tutorial1Sm}
    Diagram Id: n0
    Children count: 3
    Behaviors count: 0
    Incoming transitions count: 0

Exception VertexValidationException : State machines must have exactly 1 initial state. Actual count: 0.
   at StateSmith.Compiling.SpecificVertexValidator.Visit(Statemachine v) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/SpecificVertexValidator.cs:line 49
   at StateSmith.Compiling.Statemachine.Accept(VertexVisitor visitor) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/Statemachine.cs:line 43
   at StateSmith.Compiling.Compiler.Validate() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/Compiler.cs:line 84
   at StateSmith.Runner.SmRunner.RunCompiler() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 132
   at StateSmith.Runner.SmRunner.RunInner() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 47
   at StateSmith.Runner.SmRunner.Run() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 56
```

**Comment by adamfk** [comment]
`console output`
```
StateSmith Runner - Compiling file: `src/Tutorial1Sm.graphml` (no state machine name specified).
Exception ArgumentException : State machine name not specified. Expected diagram to have find 1 Statemachine node at root level. Instead, found 2.
==========================
Caused by below exception:
Exception InvalidOperationException : Sequence contains more than one element
Additional exception detail dumped to file: Tutorial1Sm.graphml.err.txt
StateSmith Runner - finished with failure.
```

`Tutorial1Sm.graphml.err.txt`
```
Exception ArgumentException : State machine name not specified. Expected diagram to have find 1 Statemachine node at root level. Instead, found 2.
   at StateSmith.compiler.ExtensionMethods.RunOrWrapException(Action action, Func`2 exceptionBuilder) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/ExtensionMethods.cs:line 27
   at StateSmith.Runner.SmRunner.FindStateMachine() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 122
   at StateSmith.Runner.SmRunner.RunRest() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 88
   at StateSmith.Runner.SmRunner.RunInner() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 49
   at StateSmith.Runner.SmRunner.Run() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 57
==========================
Caused by below exception:
Exception InvalidOperationException : Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at StateSmith.Runner.SmRunner.<FindStateMachine>b__12_2() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 121
   at StateSmith.compiler.ExtensionMethods.RunOrWrapException(Action action, Func`2 exceptionBuilder) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/ExtensionMethods.cs:line 22
```

**Comment by adamfk** [comment]
`console output`
```
StateSmith Runner - Compiling file: `src/Tutorial1Sm.graphml` with target state machine name: `Tutorial3Sm`.
Exception ArgumentException : Couldn't find state machine in diagram with name `Tutorial3Sm`.
==========================
Caused by below exception:
Exception ArgumentException : No named vertex found with name: `Tutorial3Sm`
Additional exception detail dumped to file: Tutorial1Sm.graphml.err.txt
StateSmith Runner - finished with failure.
```

`Tutorial3Sm.graphml.err.txt`
```
Exception ArgumentException : Couldn't find state machine in diagram with name `Tutorial3Sm`.
   at StateSmith.compiler.ExtensionMethods.RunOrWrapException(Action action, Func`2 exceptionBuilder) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/ExtensionMethods.cs:line 27
   at StateSmith.Runner.SmRunner.FindStateMachine() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 116
   at StateSmith.Runner.SmRunner.RunRest() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 88
   at StateSmith.Runner.SmRunner.RunInner() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 49
   at StateSmith.Runner.SmRunner.Run() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 57
==========================
Caused by below exception:
Exception ArgumentException : No named vertex found with name: `Tutorial3Sm`
   at StateSmith.compiler.VertexLinqHelpers.Descendant(IEnumerable`1 vertices, String name) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/VertexLinqHelpers.cs:line 39
   at StateSmith.Compiling.Compiler.GetVertex(String name) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/Compiler.cs:line 144
   at StateSmith.Runner.SmRunner.<FindStateMachine>b__12_0() in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/Runner/Runner.cs:line 115
   at StateSmith.compiler.ExtensionMethods.RunOrWrapException(Action action, Func`2 exceptionBuilder) in /mnt/c/Users/adamf/Documents/adam/code/ss/StateSmith/src/StateSmith/compiler/ExtensionMethods.cs:line 22
```
